baseurl = "https://macdang.github.io"
languageCode = "en-us"
title = "Macdang"
theme = "dario"
pygmentsstyle = "emacs"
pagination.pagerSize = 10

[markup.goldmark.renderer]
unsafe=true

[params]
  author = "Jack" # the author of the site
  description = "A description of your site" # a description of your site that will be used in the meta tags

  [params.homeInfoParams]
    Title = "MacDang" # the text to display on the "/" homepage
    Content = "This is a minimal web log inspired by Dario Amodei's personal [website](https://darioamodei.com/). Add some more text here that will be displayed on your homepage (you can use markdown)."
    Description = "A minimal web log." # The description of the home page that will be used in the open graph meta tags

